export enum ErrorCode {
  // General
  APP_ERROR = 'APP_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',

  // Token
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_TYPE_INVALID = 'TOKEN_TYPE_INVALID',

  // Session
  SESSION_INVALID = 'SESSION_INVALID',
  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',

  // Profile
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  // Email
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  //Password
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  INVALID_RELATION = 'INVALID_RELATION',
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',

  //Redis
  TOO_MANY_REQUEST_EXCEPTION = 'TOO_MANY_REQUEST_EXCEPTION',
}
