services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend
    ports:
      - "3002:3002"
    env_file:
      - ./apps/backend/.env.development
    secrets:
      - auth_jwt_private_key
      - auth_jwt_public_key
      - email_jwt_private_key
      - email_jwt_public_key
      - reset_jwt_private_key
      - reset_jwt_public_key

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db

    ports:
      - "5432:5432"

    volumes:
      - pgData:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgData:
  backend_node_modules:

secrets:
  auth_jwt_private_key:
    file: ./secrets/auth/private.pem
  auth_jwt_public_key:
    file: ./secrets/auth/public.pem
  email_jwt_private_key:
    file: ./secrets/email/private.pem
  email_jwt_public_key:
    file: ./secrets/email/public.pem
  reset_jwt_private_key:
    file: ./secrets/reset/private.pem
  reset_jwt_public_key:
    file: ./secrets/reset/public.pem
